"""Trading signal models."""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from enum import Enum


class SignalAction(Enum):
    """Trading signal actions."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderType(Enum):
    """Order types."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP_LOSS = "STOP_LOSS"


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy."""
    symbol: str
    action: SignalAction
    quantity: int
    order_type: OrderType
    limit_price: Optional[float] = None
    timestamp: datetime = None

    def __post_init__(self):
        """Validate signal and set defaults."""
        if self.timestamp is None:
            self.timestamp = datetime.now()
        
        # Convert string to enum if needed
        if isinstance(self.action, str):
            self.action = SignalAction(self.action)
        if isinstance(self.order_type, str):
            self.order_type = OrderType(self.order_type)
        
        # Validate quantity
        if self.quantity <= 0:
            raise ValueError(f"Quantity must be positive, got {self.quantity}")
        
        # Validate limit price for limit orders
        if self.order_type == OrderType.LIMIT and self.limit_price is None:
            raise ValueError("Limit orders require a limit_price")
        
        # Validate stop price for stop-loss orders
        if self.order_type == OrderType.STOP_LOSS and self.limit_price is None:
            raise ValueError("Stop-loss orders require a limit_price (stop price)")
        
        if self.limit_price is not None and self.limit_price <= 0:
            raise ValueError(f"Limit price must be positive, got {self.limit_price}")
